title: LS Tripal Tutorials
email:
author: Lacey-Anne Sanderson
description: > # this means to ignore newlines until "baseurl:"
  A tutorial on how to create a Tripal/Drupal service for a Genome Assembly
  search/access Service using dependency injection.

# Add your baseurl here (your repository)
baseurl: "/lstrptut_s4rnhy"

# This is mostly for testing
# url: "https://vsoch.github.io" # the base hostname & protocol for your site

# Keywords (space separated)
keywords: "tripal tripal4 tutorial drupal9"

# Add colorful permalinks to headers
# change colors in _includes/permalinks.html
add_permalinks: true

# Optional
support: https://github.com/LS-TripalTutorials/lstrptut_s4rnhy/issues
repo: https://github.com/LS-TripalTutorials/lstrptut_s4rnhy
github_user: laceysanderson
github_repo: lstrptut_s4rnhy

# If you have a logo, put here to include in meta tags
logo: assets/img/tw-jekyll.png

# branch to edit on GitHub
github_branch: 4.x

# If not set, badge color (background) defaults to violet
badge_color: "#371757"
badge_rounded: true

# Build settings
markdown: kramdown

# If you add tags to pages, define this variable to link them to some external search
# If you want to link to tags locally on the site, leave this commented out
# tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: primary # danger, success, warning, primary, info, secondary

accentColor: green # purple, green, etc.
themeColor: green # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
