title: LS Tripal Tutorials
email:
author: Lacey-Anne Sanderson
description: > # this means to ignore newlines until "baseurl:"
  A tutorial on how to create a Tripal/Drupal service for a Genome Assembly
  search/access Service using dependency injection.

# Add your baseurl here (your repository)
baseurl: "/lstrptut_s4rnhy"

# This is mostly for testing
# url: "https://vsoch.github.io" # the base hostname & protocol for your site

# Keywords (space separated)
keywords: "tripal tripal4 tutorial drupal9"

# Add colorful permalinks to headers
# change colors in _includes/permalinks.html
add_permalinks: true

# Optional
support: https://github.com/LS-TripalTutorials/lstrptut_s4rnhy/issues
repo: https://github.com/LS-TripalTutorials/lstrptut_s4rnhy
github_user: laceysanderson
github_repo: lstrptut_s4rnhy

# If you have a logo, put here to include in meta tags
logo: assets/img/tw-jekyll.png

# branch to edit on GitHub
github_branch: 4.x

# If not set, badge color (background) defaults to violet
badge_color: "#371757"
badge_rounded: true

# Build settings
markdown: kramdown

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
